### PR TITLE
Fix indentation to 2 spaces

### PR DESCRIPTION
**Pull request by Andrewmob2703-zz**

### CODE REVIEW

**Review by martiKallas — CHANGES_REQUESTED** [review]
It looks like your indentation got messed up somehow. Per the Google style guide, you should indent 2 spaces at a time: https://google.github.io/styleguide/htmlcssguide.html#Indentation. If you are using a custom editor, it could be that it has it's default indentation set to 4 spaces instead of two. Also, the closing tag should be at the same indentation as the opening tag.

**Review by peizhaoou — COMMENTED** [review]
Also, as Marti mentioned in the weekly sync, a general practice is to make each commit smaller. For example, you added a few blocks in this, conact_me page, gallery, meme, etc., which can be seen as functional units added together, but can also be separated logically.

The reason to spreading commits to more self-contained units is (1) easier to review and spot an error and (2) if something needs to be reverted for some reason, we can just revert the relevant parts.

**Review by peizhaoou — APPROVED** [review]

**Comment by peizhaoou** [comment]
Thanks for the change Andrew!

**Review by martiKallas — APPROVED** [review]
Looks good!

**Pull request merged**
